dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
networks:
  sepolia:
    weth_token : "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"
    lending_pool_addresses_provider: '0x012bAC54348C0E635dCAc9D5FB99f06F24136C9A'
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses_provider: '0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e'
  mainnet:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
dotenv: .env
wallets:
  from_key: "${PRIVATE_KEY}"